mode = "dev"

[jwt]
login_key = "youshangjiao"
login_path = "/user/login"
auth_key = "youshangjiao"
auth_lifetime = 7200

[http]
address = "0.0.0.0:8080"

[orm]
# https://gitea.com/xorm/xorm
# 推荐cpu核心数
orm_idle = 4
# 推荐cpu核心数*2
orm_open = 8
# 显示sql
orm_show = true
# 同步表结构
orm_sync = true
# 是否使用orm缓存
orm_cache_use = false
# orm缓存数量
orm_cache_size = 1000
# orm劫持日志输出
orm_hijack_log = true

[db]
# https://github.com/go-sql-driver/mysql
# 数据库地址
db_host = "192.168.6.96"
# 数据库端口
db_port = 3306
# 数据库账号
db_user = "root"
# 数据库密码
db_passwd = "ceshimysql123456"
# 数据库名称
db_name = "ipsky3_feedback"
# 数据库参数
db_params = "charset=utf8mb4"
